import React, { useState, useEffect } from 'react';
import { supabase } from '../supabaseClient';
import { 
  Lightbulb, Save, Edit3, Loader2, BookOpen, 
  Clock, Download, FileText, Trash2, PlusCircle, 
  ExternalLink, Zap, Database, Search
} from 'lucide-react';
import { jsPDF } from "jspdf";

export default function SubjectNotes({ user }) {
  // --- 1. CONFIGURATION & STATE ---
  // 🔥 EXPANDED: Includes your new RRB/CSE subjects
  const coreSubjects = ["Computer Science", "Reasoning", "Aptitude", "General Awareness", "Maths", "Physics", "Chemistry", "English"];
  
  const [selectedSubject, setSelectedSubject] = useState(coreSubjects[0]);
  const [personalNote, setPersonalNote] = useState('');
  const [isSaving, setIsSaving] = useState(false);
  const [lastSaved, setLastSaved] = useState(null);
  const [allNotes, setAllNotes] = useState([]);
  const [libraryResources, setLibraryResources] = useState([]); // 🔥 NEW: PDF State
  const [loading, setLoading] = useState(true);

  // --- 2. DATA SYNCHRONIZATION ---
  useEffect(() => {
    fetchAllData();
  }, [user.id]);

  useEffect(() => {
    if (selectedSubject) fetchPersonalNote();
  }, [selectedSubject, user.id]);

  const fetchAllData = async () => {
    setLoading(true);
    // Fetch Notes
    const { data: notesData } = await supabase
      .from('subject_notes')
      .select('*')
      .eq('user_id', user.id)
      .order('updated_at', { ascending: false });
    
    // 🔥 NEW: Fetch PDFs from Library
    const { data: pdfData } = await supabase
      .from('study_materials')
      .select('*')
      .order('created_at', { ascending: false });

    if (notesData) setAllNotes(notesData);
    if (pdfData) setLibraryResources(pdfData);
    setLoading(false);
  };

  const fetchPersonalNote = async () => {
    const { data } = await supabase
      .from('subject_notes')
      .select('content, updated_at')
      .eq('user_id', user.id)
      .eq('subject', selectedSubject)
      .maybeSingle(); 
    
    setPersonalNote(data?.content || '');
    if (data?.updated_at) {
        setLastSaved(new Date(data.updated_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }));
    } else {
        setLastSaved(null);
    }
  };

  // --- 3. ACTIONS (SAVE, DELETE, EXPORT) ---
  const handleSaveNote = async () => {
    if (!personalNote.trim()) return;
    setIsSaving(true);
    const { error } = await supabase
      .from('subject_notes')
      .upsert({ 
        user_id: user.id, 
        subject: selectedSubject, 
        content: personalNote,
        updated_at: new Date()
      }, { onConflict: 'user_id,subject' });
    
    if (!error) {
        setLastSaved(new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }));
        fetchAllData(); // Refresh list
    }
    setTimeout(() => setIsSaving(false), 600);
  };

  const handleDeleteNote = async (id) => {
    if (!window.confirm("The Brain, delete this note permanently?")) return;

    const { error } = await supabase
      .from('subject_notes')
      .delete()
      .eq('id', id);

    if (!error) {
      const remainingNotes = allNotes.filter(n => n.id !== id);
      setAllNotes(remainingNotes);
      // Clear editor if the deleted note was the currently selected one
      if (allNotes.find(n => n.id === id)?.subject === selectedSubject) {
        setPersonalNote('');
        setLastSaved(null);
      }
    }
  };

  const downloadAsPDF = (noteContent, subject) => {
    if (!noteContent) return;
    const doc = new jsPDF();
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(37, 99, 235);
    doc.text(`${subject} // Neural Transcript`, 20, 20);
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(150);
    doc.text(`Generated by The Brain Portal | ${new Date().toLocaleString()}`, 20, 30);
    doc.line(20, 35, 190, 35);
    
    doc.setFontSize(12);
    doc.setTextColor(0);
    const splitText = doc.splitTextToSize(noteContent, 170);
    doc.text(splitText, 20, 45);
    
    doc.save(`${subject}_Neural_Note.pdf`);
  };

  // Filter PDFs based on selected subject
  const relevantPDFs = libraryResources.filter(res => 
    res.subject === selectedSubject || res.subject === 'General'
  );

  return (
    <div className="space-y-8 pb-20 animate-in fade-in duration-500">
      
      {/* 1. SUBJECT NAVIGATION STRIP */}
      <div className="flex gap-3 overflow-x-auto pb-2 custom-scrollbar p-1">
        {coreSubjects.map((sub) => (
          <button 
            key={sub}
            onClick={() => setSelectedSubject(sub)}
            className={`px-6 py-3 rounded-2xl font-black transition-all text-[10px] uppercase tracking-widest whitespace-nowrap ${
              selectedSubject === sub 
              ? 'bg-blue-600 text-white shadow-lg shadow-blue-500/30 scale-105' 
              : 'bg-white dark:bg-gray-800 text-gray-400 hover:bg-gray-50 dark:hover:bg-gray-700'
            }`}
          >
            {sub}
          </button>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 items-start">
        
        {/* 2. EDITOR (Takes up 2 columns) */}
        <div className="lg:col-span-2 space-y-6">
          <div className="bg-white dark:bg-gray-800 p-8 rounded-[2.5rem] shadow-xl border dark:border-gray-700 relative overflow-hidden">
            <div className="absolute top-0 right-0 p-10 opacity-5 pointer-events-none">
              <Edit3 size={120} />
            </div>
            
            <div className="relative z-10">
              <div className="flex justify-between items-center mb-6">
                <div>
                  <h3 className="text-3xl font-black text-gray-800 dark:text-white uppercase tracking-tighter">
                    {selectedSubject}
                  </h3>
                  <div className="flex items-center gap-2 mt-1">
                    {lastSaved ? (
                      <span className="text-[10px] text-green-500 font-bold uppercase tracking-widest flex items-center gap-1"><Zap size={10} /> Synced {lastSaved}</span>
                    ) : (
                      <span className="text-[10px] text-gray-400 font-bold uppercase tracking-widest">Unsaved Changes</span>
                    )}
                  </div>
                </div>
                
                <div className="flex gap-2">
                  <button onClick={() => downloadAsPDF(personalNote, selectedSubject)} className="p-3 bg-gray-100 dark:bg-gray-700 rounded-xl text-gray-500 hover:text-blue-600 transition-colors" title="Export PDF">
                    <Download size={20} />
                  </button>
                  <button 
                    onClick={handleSaveNote}
                    disabled={isSaving}
                    className="flex items-center gap-2 bg-blue-600 text-white px-6 py-3 rounded-xl font-black uppercase text-xs tracking-widest hover:bg-blue-700 shadow-lg active:scale-95 disabled:opacity-50 transition-all"
                  >
                    {isSaving ? <Loader2 className="animate-spin" size={16} /> : <Save size={16} />}
                    {isSaving ? 'Syncing...' : 'Save Node'}
                  </button>
                </div>
              </div>

              <textarea 
                className="w-full h-[500px] p-6 rounded-[1.5rem] border-2 border-gray-100 dark:border-gray-700 focus:border-blue-500 dark:focus:border-blue-500 bg-gray-50 dark:bg-gray-900 dark:text-white shadow-inner resize-none font-medium leading-loose text-base outline-none transition-all custom-scrollbar"
                placeholder={`Initialize neural stream for ${selectedSubject}...`}
                value={personalNote}
                onChange={(e) => setPersonalNote(e.target.value)}
              />
            </div>
          </div>
        </div>

        {/* 3. CONTEXT SIDEBAR (PDFs + History) */}
        <div className="space-y-6">
          
          {/* A. RELEVANT LIBRARY RESOURCES (PDFs) */}
          <div className="bg-white dark:bg-gray-800 p-6 rounded-[2.5rem] shadow-xl border dark:border-gray-700">
            <div className="flex items-center gap-3 mb-6 pb-4 border-b dark:border-gray-700">
              <Database size={20} className="text-orange-500" />
              <h4 className="font-black uppercase text-sm dark:text-white tracking-wide">Library Nodes</h4>
            </div>
            
            {relevantPDFs.length > 0 ? (
              <div className="space-y-3 max-h-[300px] overflow-y-auto custom-scrollbar pr-2">
                {relevantPDFs.map((res) => (
                  <a 
                    key={res.id} 
                    href={res.url} 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="block p-4 rounded-2xl bg-gray-50 dark:bg-gray-900/50 hover:bg-orange-50 dark:hover:bg-orange-900/10 border border-transparent hover:border-orange-200 transition-all group"
                  >
                    <div className="flex justify-between items-start">
                      <div className="flex-1">
                        <h5 className="font-bold text-xs dark:text-white line-clamp-2 leading-tight group-hover:text-orange-600 transition-colors">{res.title}</h5>
                        <p className="text-[8px] font-black text-gray-400 uppercase mt-2 flex items-center gap-1">
                          <FileText size={8} /> PDF Resource
                        </p>
                      </div>
                      <ExternalLink size={12} className="text-gray-300 group-hover:text-orange-500" />
                    </div>
                  </a>
                ))}
              </div>
            ) : (
              <div className="text-center py-10 opacity-50">
                <BookOpen size={32} className="mx-auto text-gray-300 mb-2" />
                <p className="text-[10px] font-black uppercase text-gray-400">No PDFs Indexed</p>
                <p className="text-[8px] text-gray-300 mt-1">Upload via Admin Panel</p>
              </div>
            )}
          </div>

          {/* B. NOTE HISTORY */}
          <div className="bg-white dark:bg-gray-800 p-6 rounded-[2.5rem] shadow-xl border dark:border-gray-700">
            <div className="flex items-center gap-3 mb-6 pb-4 border-b dark:border-gray-700">
              <Clock size={20} className="text-blue-600" />
              <h4 className="font-black uppercase text-sm dark:text-white tracking-wide">Recent Edits</h4>
            </div>
            
            <div className="space-y-3 max-h-[250px] overflow-y-auto custom-scrollbar pr-2">
              {allNotes.length > 0 ? (
                allNotes.map((note) => (
                  <div key={note.id} className="group flex items-center justify-between p-3 rounded-xl hover:bg-blue-50 dark:hover:bg-blue-900/20 transition-all cursor-pointer" onClick={() => { setSelectedSubject(note.subject); setPersonalNote(note.content); }}>
                    <div className="flex items-center gap-3 overflow-hidden">
                      <div className={`w-1.5 h-8 rounded-full ${note.subject === selectedSubject ? 'bg-blue-600' : 'bg-gray-200'}`}></div>
                      <div>
                        <p className="font-bold text-[10px] dark:text-white uppercase truncate w-32">{note.subject}</p>
                        <p className="text-[8px] text-gray-400 font-bold">{new Date(note.updated_at).toLocaleDateString()}</p>
                      </div>
                    </div>
                    <button 
                      onClick={(e) => { e.stopPropagation(); handleDeleteNote(note.id); }}
                      className="text-gray-300 hover:text-red-500 p-2 opacity-0 group-hover:opacity-100 transition-all"
                    >
                      <Trash2 size={14} />
                    </button>
                  </div>
                ))
              ) : (
                <p className="text-center text-[10px] font-bold text-gray-400 py-4">No active nodes.</p>
              )}
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}